# Generated by Django 4.2.5 on 2023-09-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catgeory',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
