# Generated by Django 4.2.5 on 2023-09-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgeory',
            new_name='Category',
        ),
    ]
