# Generated by Django 4.1.5 on 2023-10-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
