# Generated by Django 4.2.5 on 2023-12-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_brand'),
        ('Guest', '0002_remove_userregistration_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.place'),
        ),
    ]
