# Generated by Django 4.2.5 on 2023-12-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_userregistration_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='district',
        ),
    ]
