# Generated by Django 4.2.5 on 2023-12-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_remove_userregistration_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
