# Generated by Django 4.2.5 on 2023-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_userregistration_contact_userregistration_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='file',
            field=models.FileField(null=True, upload_to='userdocs/'),
        ),
    ]
